defaults:
  - base_view_sampler

min_distance_between_context_views: 8
max_distance_between_context_views: 22
min_distance_to_context_views: 0
initial_min_distance_between_context_views: 5
initial_max_distance_between_context_views: 7
