defaults:
  - base_view_sampler

min_distance_between_context_views: 5
max_distance_between_context_views: 15
min_distance_to_context_views: 0
initial_min_distance_between_context_views: 5
initial_max_distance_between_context_views: 5
