defaults:
  - model/encoder: noposplat
  - loss: []
  - override dataset/view_sampler@dataset.re10k.view_sampler: evaluation

dataset:
  re10k:
    view_sampler:
      index_path: assets/evaluation_index_re10k.json

data_loader:
  train:
    num_workers: 0
    persistent_workers: true
    batch_size: 1
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 0
    persistent_workers: true
    batch_size: 1
    seed: 3456

seed: 111123
